### PR TITLE
remove duplicate nicegui dependencies

### PR DESCRIPTION
**Pull request by NiklasNeugebauer**
Many dependencies are already included in nicegui and have conflicting version with the ones used in nicegui 1.2.13 (which is currently used by the base_node.dockerfile and thus by all others based on it).

By removing the explicit dependencies here, we would avoid overwriting them and breaking something in nicegui.

### CODE REVIEW

**Review by rodja — APPROVED** [review]
Yes, good idea! But we should also think about updating to latest NiceGUI. There are a huge number of new features and bugfixes.

**Comment by rodja** [comment]
Oh, it broke the build: https://github.com/zauberzeug/learning_loop_node/actions/runs/7406821103/job/20151886075
Could you look into this, @NiklasNeugebauer?

**Comment by NiklasNeugebauer** [comment]
I supposed it is needed then since nicegui is not a real dependency but just used as the docker container base and really it should not be. 
I updated the packages accordingly and will look into an update of the container in light of the planned Python version update

**Comment by NiklasNeugebauer** [comment]
See updated pull request #7

**Pull request merged**
